---
title: "Discs"
author: "Josh Baber"
date: "7/13/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(psych)
library(rpart)
library(randomForest)
library(rattle)
```

```{r}
allDiscs <- read_csv("../Data/discs.csv")
```

```{r}
names(allDiscs)
```

```{r}
summary(allDiscs)
```

```{r}
fullSeason <- read_csv("../Data/udisclive.csv")
fullSeason <- fullSeason[-c(1, 220),-c(3, 5, 7, 13, 19, 20)]
```

```{r}
colnames(fullSeason) <- c("Place", "Name", "Birdie", "Par", "Bogey", "Fairway", "Parked", 
                          "Circle1InReg", "Circle2InReg", "Scramble", "Circle1XPutting", 
                          "Circle2Putting", "ThrowInRate", "OBRate")
```

```{r}
fullSeason$Place <- as.numeric(sub("T", "", fullSeason$Place))
```

```{r}
fullSeason[,c(3:12)] <- data.frame(sapply(fullSeason[,c(3:12)], function(x){as.numeric(gsub("%", "", x))}))
```

```{r}
points <- read_csv("../Data/Udiscpoints.csv")
points <- points[,-c(1,4)]
colnames(points) <- c("Name", "Points")
```

```{r}
fullSeason <- left_join(fullSeason, points, by = c("Name" = "Name"))
fullSeason$Points <- as.numeric(fullSeason$Points)
fullSeason$OBRate <- fullSeason$OBRate*100
fullSeason$ThrowInRate <- fullSeason$ThrowInRate*100
```

```{r}
head(fullSeason)
```

```{r}
scoresData <- fullSeason[,-c(1,2)]
lm(Points ~ ., data = scoresData)
```

```{r}
ggplot(data = fullSeason, aes(x = Bogey)) + geom_boxplot()
```

```{r}
colMeans(scoresData)
```

```{r}
scoresData %>% colMeans()
```

```{r}
split <- createDataPartition(scoresData$Points, p = 0.8, list = FALSE)
trainScores <- scoresData[split,]
testScores <- scoresData[-split,]
```

```{r}
varnames <- paste0(c("Birdie", "Par", "Bogey", "Fairway", "Parked", "Circle1InReg", "Circle2InReg", "Scramble", "Circle1XPutting", 
                        "Circle2Putting", "ThrowInRate", "OBRate"), collapse = "+")
squaredvarnames <- paste0("(", varnames, ")^2")
response <- "Points"
mlr <- train(as.formula(paste(response, varnames, sep = " ~ ")),
             data = trainScores, method = "lm", 
             trControl = trainControl(method = "repeatedcv", number = 5, repeats = 3),
             preProcess = c("center", "scale"))
intMLR <- mlr <- train(as.formula(paste(response, squaredvarnames, sep = " ~ ")),
             data = trainScores, method = "lm", 
             trControl = trainControl(method = "repeatedcv", number = 5, repeats = 3),
             preProcess = c("center", "scale"))
```

```{r}
regTree <- train(as.formula(paste(response, varnames, sep = " ~ ")),
                 data = trainScores, method = "rpart",
                 trControl = trainControl(method = "repeatedcv", number = 5, repeats = 3),
                 preProcess = c("center", "scale"),
                 tuneGrid = expand.grid(cp = seq(from = 0, to = 0.1, by = 0.001)))
```

```{r}
rf <- train(as.formula(paste(response, varnames, sep = " ~ ")), data = trainScores, method = "rf",
                        # Perform 5 fold cross validation repeated 3 times
                        trControl = trainControl(method = "repeatedcv", number = 5, repeats = 3),
                        # Standardize the data
                        preProcess = c("center", "scale"),
                        # Check all possible m values from 1 to 15
                        tuneGrid = expand.grid(mtry = c(1:12)),
                        importance = TRUE)
```

```{r}
data.frame(mlr$results$RMSE,
intMLR$results$RMSE,
min(regTree$results$RMSE),
min(rf$results$RMSE))
```

```{r}
imp<-varImp(rf)
imp$importance
```

```{r}
mlrPred <- predict(mlr, newdata = testScores)
regTreePred <- predict(regTree, newdata = testScores)
rfPred <- predict(rf, newdata = testScores)
errorTab <- data.frame(
postResample(mlrPred, obs = testScores$Points),
postResample(regTreePred, obs = testScores$Points),
postResample(rfPred, obs = testScores$Points)
)
colnames(errorTab) <- c("MLR", "RegTree", "RandomForest")
errorTab
```

```{r}
mlrNew <- train(Points ~ Bogey + Circle1XPutting + OBRate,
             data = trainScores, method = "lm", 
             trControl = trainControl(method = "repeatedcv", number = 5, repeats = 3),
             preProcess = c("center", "scale"))
```

```{r}
plot(regTree$finalModel)
text(regTree$finalModel)
```



